### ISSUE TITLE
Xcode 12.2 / Swift 5.3.1

### ISSUE THREAD

**Issue by johnrogers** [birdrides/mockingbird#179]
👋 

Hello,

Could we get an updated binary that's built with Swift 5.3.1, please?

Thank you!

**Comment by andrewchang-bird** [comment]
Here’s some artifacts built with Swift 5.3: https://github.com/birdrides/mockingbird/actions/runs/366959884

Let me know if this works for you; will cut a patch by end of week.

**Comment by neuralmer** [comment]
I am trying out Mockingbird, and I too am using Xcode 12.2 / Swift 5.3.1. I am running into problems trying to do any stubbing: `given is not in scope`. Adding `import Mockingbird` fixed this -- I was able to call `mock()` without this and didn't realize it was necessary in order to call `given()`: I don't see the import step mentioned in the instructions.

I have installed Mockingbird using Swift Package Manager, setting the commit to use to be 064f8666012befb0faa7cb858ca112da2bdb7e05. Since v0.16.1 isn't released some of the installation instructions won't work. I manually updated the MockingbirdSupport directory, but it doesn't look like there were any changes to the support files. I updated the `mockingbird` binary. I reinstalled Mockingbird in the test target. Doing these things, this test build appears to work correctly (I am able to mock, stub, and verify for a very simple example).

I do however get a warning: `Module 'Mockingbird' was not compiled with library evolution support; using it means binary compatibility for 'MyXCFrameworkTests' can't be guaranteed`. Is there a reason why library evolution support is not enabled?

**Comment by neuralmer** [comment]
As far as supporting Xcode 12.2, I am seeing warnings about the targeted version of iOS. `The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99.` My project is targeting iOS 12.0, and I believe that this 8.0 setting is from Mockingbird, perhaps Mockingbird's `Package.swift` since I am including it via Swift Package Manager.
