### ISSUE TITLE
MockingBird crashing in build phase

### ISSUE THREAD

**Issue by Marcin951** [birdrides/mockingbird#192]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

I can't build the project without the crash after install MockingBird

### Generator Bugs

error message after crash on building project

<img width="1093" alt="Zrzut ekranu 2021-02-11 o 21 49 03" src="https://user-images.githubusercontent.com/31135444/107697044-01cba080-6cb3-11eb-8fdd-0e5e738205db.png">

`/Users/marcinkaczmarzyk/Library/Developer/Xcode/DerivedData/Hangable-fjncjlqekoqfrgdniczrzmekgrbv/Build/Intermediates.noindex/Hangable.build/Debug-iphonesimulator/HangableTests.build/Script-CD7B4D3D7240BAE4C304CE9C.sh: line 7: 68371 Illegal instruction: 4  mockingbird generate --targets 'Hangable' --outputs "${SRCROOT}/MockingbirdMocks/HangableTests-HangableMocks.generated.swift" --support "${SRCROOT}/MockingbirdSupport"
Command PhaseScriptExecution failed with a nonzero exit code`

### Framework Bugs

It's crashing in build phase

## Environment
That is how my Podfile looks 

`platform :ios, '13.0'

target 'Hangable' do
  use_frameworks!
  inhibit_all_warnings!
  
  # Pods for Hangable
    pod 'Firebase/Core'
    ........
end

target 'HangableTests' do
  inherit! :complete
    pod 'MockingbirdFramework'
end

 post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end

`

* Mockingbird CLI version (`mockingbird version`) 0.16
* Xcode and macOS version (are you running a beta?) Xcode 12.4, Mac OS 11.2.1 no beta software
* Swift version (`swift --version`) Swift 5.3.2
* Installation method (CocoaPods, Carthage, from source, etc) CocoaPods
* Unit testing framework (XCTest, Quick + Nimble, etc) XCTest
* Does your project use `.mockingbird-ignore`? No
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? yes

**Comment by andrewchang-bird** [comment]
Thanks for the report! It’s likely due to a parser issue (we’re tracking a few right now). If you have a few min running the generator locally running and pointing it to your project + `Hangable` source target should show the exact line(s) and file(s) that it’s breaking on, which you can then add to `.mockingbird-ignore`:

1. Follow the environment setup steps here https://github.com/birdrides/mockingbird/wiki/Local-Development
2. Select MockingbirdCli as the target
3. Edit the scheme (cmd + shift + comma) and change the launch arguments to `generate --project <your_project> --target Hangable --output /tmp/unused`
4. Run the CLI and screenshot / post the logs of where it crashes
5. Add the file to `.mockingbird-ignore`
6. Repeat from (4) until it doesn’t crash anymore
