### ISSUE TITLE
Library evolution support is broken

### ISSUE THREAD

**Issue by ugomarinelli** [birdrides/mockingbird#242]
Hello, 

We are currently blocked when using XCode 13.2, with this message: 

`Failed to build module 'Mockingbird'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK`.

Do you have any plans to support XCode 13.2 in the future ? 
Thank you !

**Comment by andrewchang-bird** [comment]
Thanks for filing. Which package manager are you using? If you build the framework from source or via SPM does it still raise this error?

Anyway, I am working on Swift 5.5.2 / Xcode 13.2 support. The framework side is trivial, but unfortunately the CLI does require us to migrate from the old SPM utils to Swift Argument Parser.

**Comment by andrewchang-bird** [comment]
So the issue is that library evolution support isn’t working even though it’s enabled for the framework; `BUILD_LIBRARY_FOR_DISTRIBUTION = YES` and a Swift module interface is generated with `-enable-library-evolution` listed in the module flags. Seems like it might be something with how Swift is doing library evolution as there are known problems (https://github.com/realm/realm-swift/issues/7313), but I’m not able to isolate the issue using a minimal framework and project.

In the meantime, you should build the framework from source. If you’re using Carthage, you’ll need to run `carthage build` whenever changing Xcode toolchains / Swift versions.
