### ISSUE TITLE
Missing inOrder verification

### ISSUE THREAD

**Issue by paiv** [birdrides/mockingbird#48]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

Verification needs a way to check the order of invoked mocks.

For example,

```swift
protocol Some {
    func foo()
    func bar()
}

func example(_ some: Some) {
    some.bar()
    some.foo()
}
```

```swift
func test_example() {
    let some = mock(Some.self)
    let inOrder = inOrder(some)
    
    example(some)

    // failing
    // inOrder.verify(some.foo()).wasCalled(once)
    // inOrder.verify(some.bar()).wasCalled(once)

    // passing
    inOrder.verify(some.bar()).wasCalled(once)
    inOrder.verify(some.foo()).wasCalled(once)
}
```

## Environment

* Mockingbird CLI version `0.9.0`
* Xcode `11.3.1` macOS version `10.15.3`
* Swift version `Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)`
* Installation method `CocoaPods`

**Comment by andrewchang-bird** [comment]
Thanks for filing! In-order verification is something we initially deprioritized because it felt like it could encourage devs to write more brittle code and tests. That said, I do see where specifying the order as an invariant could be useful.

In terms of syntax, the most elegant way I’ve come up with is similar to the asynchronous verification block, something like:

```swift
strictly {
  verify(foo.bar()).wasCalled
